

# Setup
title:               Your Blog Title
theme:                jekyll-theme-slate
tagline:             ''
description:         ''
home:                http://mikromika.github.io
url:                 http://mikromika.github.io/blog
baseurl:             /BLOG/
paginate:            5
paginate_path:       "/page:num/"
exclude:             ['posts']
