
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Mikromike
tagline:          'A Jekyll theme'
description:      'Mikromikes homepage '
url:              https://mikromika.github.io
baseurl:          /

author:
  name:           'Mikromike'
  url:

pages_list:
  About: '/blog_name/about'



paginate:         5
paginate_path:       "/page:num/"

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/mikromika/mikromika.github.com.git
