
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Mikromike
tagline:          'A Jekyll theme'
description:      'Mikromike's homepage <a href="https://mikromika.github.io/" target="_blank">Mikromike</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mikrmike'
  url:            https://twitter.com/mdo

paginate:         5There are currently two themes built on PoolThere are currently two themes built on Poole:

* [Hyde](http://hyde.getpoole.com)
* [Lanyon](http://lanyon.getpoole.com)

Learn more and contribute on [GitHub](https://github.com/poole).
e:

* [Hyde](http://hyde.getpoole.com)
* [Lanyon](http://lanyon.getpoole.com)


# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/mikromika/mikromika.github.com.git
