
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Mikromike
tagline:          'A Jekyll theme'
description:      'Mikromikes homepage '
url:              https://mikromika.github.io
baseurl:          /

author:
  name:           'Mikromike'
  url:

pages_list:
  About: '/blog_name/about'

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
input: GFM

paginate:         5
paginate_path:       "/page:num/"

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/mikromika/mikromika.github.com.git

  # Use the following plug-ins
gems:
- jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
- jekyll-feed # Create an Atom feed using the official Jekyll feed gem
