
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Mikromike
tagline:          'A Jekyll theme'
description:      'Mikromikes homepage '
url:              https://mikromika.github.io
baseurl:          /

author:
  name:           'Mikromike'
  url:

paginate:         5


# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/mikromika/mikromika.github.com.git
